// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzAE60LKAgl5nO8mIWWnFF-JAAp8ZxAqk',
    appId: '1:1069174984381:web:f562d8f9625d2e73a4b1d4',
    messagingSenderId: '1069174984381',
    projectId: 'notess-a1a74',
    authDomain: 'notess-a1a74.firebaseapp.com',
    storageBucket: 'notess-a1a74.firebasestorage.app',
    measurementId: 'G-X342RC88TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfRKxQXdLWxrcs5tZqT7so1hyBWhwwKdU',
    appId: '1:1069174984381:android:f56241bdfce4ed11a4b1d4',
    messagingSenderId: '1069174984381',
    projectId: 'notess-a1a74',
    storageBucket: 'notess-a1a74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPm2gCo1TD-r3bfML170Van_ZHUHbnlP8',
    appId: '1:1069174984381:ios:fcaf64268f8ef6f1a4b1d4',
    messagingSenderId: '1069174984381',
    projectId: 'notess-a1a74',
    storageBucket: 'notess-a1a74.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPm2gCo1TD-r3bfML170Van_ZHUHbnlP8',
    appId: '1:1069174984381:ios:fcaf64268f8ef6f1a4b1d4',
    messagingSenderId: '1069174984381',
    projectId: 'notess-a1a74',
    storageBucket: 'notess-a1a74.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzAE60LKAgl5nO8mIWWnFF-JAAp8ZxAqk',
    appId: '1:1069174984381:web:ec2c3677ad6c7d2ea4b1d4',
    messagingSenderId: '1069174984381',
    projectId: 'notess-a1a74',
    authDomain: 'notess-a1a74.firebaseapp.com',
    storageBucket: 'notess-a1a74.firebasestorage.app',
    measurementId: 'G-8ZD5F2NPRM',
  );
}
